service: lambda-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME}
    AWS_REGION: ${env:AWS_REGION}

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    basePath: ./